---
discord_user: "{{ global_user }}"
discord_version: discord
discord_install_betterdiscord: true

discord_betterdiscord_plugins:
  - "https://mwittrien.github.io/BetterDiscordAddons/Library/0BDFDB.plugin.js"
  - "https://mwittrien.github.io/BetterDiscordAddons/Plugins/BetterNsfwTag/BetterNsfwTag.plugin.js"
  - "https://raw.githubusercontent.com/rauenzi/BetterDiscordAddons/master/Plugins/BetterRoleColors/BetterRoleColors.plugin.js"
  - "https://raw.githubusercontent.com/QWERTxD/BetterDiscordPlugins/main/CallTimeCounter/CallTimeCounter.plugin.js"
  - "https://raw.githubusercontent.com/Farcrada/DiscordPlugins/master/Channel-Permissions/ChannelPermissions.plugin.js"
  - "https://mwittrien.github.io/BetterDiscordAddons/Plugins/CompleteTimestamps/CompleteTimestamps.plugin.js"
  - "https://mwittrien.github.io/BetterDiscordAddons/Plugins/CopyRawMessage/CopyRawMessage.plugin.js"
  - "https://raw.githubusercontent.com/TheGreenPig/BetterDiscordPlugins/main/FileViewer/FileViewer.plugin.js"
  - "https://mwittrien.github.io/BetterDiscordAddons/Plugins/GameActivityToggle/GameActivityToggle.plugin.js"
  - "https://mwittrien.github.io/BetterDiscordAddons/Plugins/GoogleSearchReplace/GoogleSearchReplace.plugin.js"
  - "https://raw.githubusercontent.com/Farcrada/DiscordPlugins/master/Hide-Channels/HideChannels.plugin.js"
  - "https://raw.githubusercontent.com/qwerasd205/BDPlugins/8c4648ab5e3dc39adec6b0bbe12d039290c1c437/PinIcon/PinIcon.plugin.js"
  - "https://mwittrien.github.io/BetterDiscordAddons/Plugins/SplitLargeMessages/SplitLargeMessages.plugin.js"
  - "https://github.com/l0c4lh057/BetterDiscordStuff/blob/master/Plugins/TypingIndicator/TypingIndicator.plugin.js"
  - "https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js"

discord_betterdiscord_themes:
  - url: https://betterdiscord.app/Download?id=124
    name: HorizontalServerList
  - url: https://raw.githubusercontent.com/maenDisease/BetterDiscordStuff/main/Themes/Float/zFloat.theme.css
    name: zFloat